cc -std=c99 -Wall read_file.c mpc.c -ledit -lm -o read_file
cc -std=c99 -Wall help.c mpc.c -ledit -lm -o help
#cc -std=c99 -Wall prompt.c -ledit -o prompt
#cc -std=c99 -Wall doge.c mpc.c -ledit -lm -o doge
#cc -std=c99 -Wall doge_grammar.c mpc.c -ledit -lm -o doge_grammar
#cc -std=c99 -Wall polish_notation.c mpc.c -ledit -lm -o polish_notation
#cc -std=c99 -Wall parsing.c mpc.c -ledit -lm -o parsing
#cc -std=c99 -Wall s_expressions.c mpc.c -ledit -lm -o s_expressions
cc -std=c99 -Wall q_expressions.c mpc.c -ledit -lm -o q_expressions
